name: Update voxxrin

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repository
permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: update
        env:
          VOXXRIN_TOKEN: ${{ secrets.VOXXRIN_TOKEN }}
        run: |
          voxxrin/voxxrin.sh update
